Vagrant.configure(2) do |config|
 # Do not pay attention to this parameter
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vm.provider :virtualbox do |vb|
      config.vbguest.auto_update = false
    end
  end

  config.vm.box = "centos/7"

  config.ssh.insert_key = false

  config.vm.define "database" do |machine|
    machine.vm.network "private_network", ip: "172.17.177.22"
    machine.vm.provision "ansible_local" do |ansible|
      ansible.verbose = true
      ansible.playbook = 'playbook.yaml'
    end
  end

    config.vm.define "web" do |machine|
      machine.vm.network "private_network", ip: "172.17.177.21"
      machine.vm.provision "ansible_local" do |ansible|
        ansible.playbook = 'playbook.yaml'
      end
    end
end
