apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-project-deployment
  labels:
    app: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: nidourah/node-web-app
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_REDIS_URL
              value: redis://redis-service:6379
