apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-project-deployment-v0.6.0
  labels:
    app: web
    version: v0.6.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
      version: v0.6.0
  template:
    metadata:
      labels:
        app: web
        version: v0.6.0
    spec:
      containers:
        - name: web
          image: nidourah/ece-devops-project:v0.6.0
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_REDIS_URL
              value: redis://redis-service:6379
            - name: AUTH_SECRET
              value: "secret"
